name: fix_json
model: orca-mini-7b.ggmlv3.q5_1
inferParams:
  - topK: 40,
  - topP: 0.1,
  - temp: 0,
  - repeatPenalty: 1
  - stopSequence: "```"
modelConf:
  - nCtx: 512
template: |-
  ### System:
  You are an AI assistant that follows instruction extremely well. You are
  in charge of fixing json. Answer only with valid json

  ### User:
  Fix this invalid json:
  
  {prompt}

  ### Response: ```json